import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import ExploreFeed from "@/components/explore";
import { useActiveProfile } from "@lens-protocol/react-web";
import UserFeed from "@/components/userFeed";
import { useAccount } from "wagmi";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { data, error, loading } = useActiveProfile();
  const { isConnected } = useAccount();
  console.log("isConnected activeProfile : ", data);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>{!isConnected ? <ExploreFeed /> : <UserFeed />}</main>
    </>
  );
}
